### ISSUE TITLE
issue with new inline strategy 

### ISSUE THREAD

**Issue by patricklx** [ghedamat/ember-svg-jar#253]
## 🐞 Bug Report

There is an issue with the inline strategy if more than 1 addon is using ember-svg-jar or app and some addon.
Then index.js gets overwritten...
This happened with an in-app addon

**Comment by patricklx** [comment]
@evoactivity maybe you need to revert the update... and use the nested try catches.

**Comment by evoactivity** [comment]
I wonder if assets that share the same name end up overwriting each other in that scenario too?

**Comment by patricklx** [comment]
Yeah, I'm quite sure they do get overwritten

**Comment by evoactivity** [comment]
I've merged and release your PR.

Test failures suddenly appeared even on master branch with no changes.

**Comment by patricklx** [comment]
👍sure. But i hope it actually works for embroider 😅

**Comment by evoactivity** [comment]
It does, I manually tested. The error is triggered by fastboot, not sure why though, that's not been updated since the last successful runs.
