### ISSUE TITLE
2.4.5: template-registry is missing

### ISSUE THREAD

**Issue by NullVoxPopuli** [ghedamat/ember-svg-jar#257]
![image](https://github.com/ghedamat/ember-svg-jar/assets/199018/442f38d3-1e96-42d8-aedf-8859a44318b5)

There is no types directory, as required per the package.json

![image](https://github.com/ghedamat/ember-svg-jar/assets/199018/ea8e0965-b25b-426b-98f7-8c5bbd1a3106)

**Comment by evoactivity** [comment]
https://github.com/ghedamat/ember-svg-jar/pull/246 didn't update the package, will push a fix now.

**Comment by evoactivity** [comment]
@NullVoxPopuli Re-open if not fixed
